version: '3'
services:
  chrome:
    image: selenium/node-chrome:4.1.3-20220405
    shm_size: 2gb
    depends_on:
      - selenium-hub
    ports:
      - "5900:5900"
      - "7900:7900"      
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      selenium-hub-network:
  edge:
    image: selenium/node-edge:4.1.3-20220405
    shm_size: 2gb
    depends_on:
      - selenium-hub
    ports:
      - "5901:5900"
      - "7901:7900"      
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      selenium-hub-network:
  firefox:
    image: selenium/node-firefox:4.1.3-20220405
    shm_size: 2gb
    depends_on:
      - selenium-hub
    ports:
      - "5902:5900"
      - "7902:7900"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      selenium-hub-network:
  selenium-hub:
    image: selenium/hub:4.1.3-20220405
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      selenium-hub-network:
networks:
  selenium-hub-network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 175.25.0.0/24